# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 68861c399a967e73c96a3aa92d605fab21c820450e5885566af48c5a58c4c096131cc545ca2268cf928a8703ac75d85ef89d34125ea7fb076e5d03875e183d83

test:
  secret_key_base: d921d6a4ebda4c4e3bd06c50a0d36577f910bdfe6070cdb8e00cc23610cf284c6ec52a0677b84e18aed3a772c6f3ac9cf9028b3d7213a09c8ac7b0a0612252da

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
